spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.11.41;databaseName=CamundaForMule
    username: affiliate
    password: passaffiliate01
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: vmail.viriyah.co.th
    port: 25
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: false
            require: false
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks

url:
  base: http://172.16.11.19 #config
  service:
    policyinfo: https://vgateway.viriyah.co.th/cdata/CoreWSDBMotorDBDev_SpGetPolicyInfoForCamunda
    policyinfoNonMotor: https://vgateway.viriyah.co.th/cdata/CoreWSDBMotorDBDev_SpGetPolicyInfoForCamundaNonMotor
    pdf:
      generate: ${url.base}/VIRGenerateDocumentGateway/api/Gateway
      protect: ${url.base}/VIRSignDocument/api/SignToECM
      sign: http://primekey.viriyah.co.th:8080/signserver/process
      send:
        online: http://10.99.5.174/Camunda_Service/uploadFile
        email: https://uat-api.viriyah.co.th/uat/gw/api/general/message/v1/communication
        sms: https://uat-api.viriyah.co.th/uat/gw/api/general/message/v1/communication
        clientId: ec81d967-0192-4680-939e-8de81980d336
        clientSecret: 02f477ad-39b9-4cc5-a151-f98323dfd60b
    ecm:
      ecmapi: https://vgateway.viriyah.co.th/filelibraryext/ws/Search
      sharelinkapi: https://vgateway.viriyah.co.th/filelibraryext/shared-links
      shortlinkdomain: https://vpol.co/
      org: viriyahdev
fixed:
  body:
    send:
      online: N
      email: N
      sms: N
  mail:
    sendOn:
      success: Y
      failed: Y
    from: camunda@viriyah.co.th
    report: >
      chakatponk@viriyah.co.th,
      pakornk@viriyah.co.th,
      weeraphotp@viriyah.co.th,
      tanawut.b@allrightbox.com
